id: P94FFFBFE
initial_creation_type: ocr
source_metadata:
  volumes:
    554f671cc2944b6bb31a239f4c34d84a:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས་སྤྱིའི་མངོན་པར་རྟོགས་པ།
      total_pages: 1856
      volume_number: 14
